spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_whit_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 87402001
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    # properties:
      # hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true